import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Experience from '../components/Experience'
import Skilss from '../components/Skilss'
import Projects from '../components/Projects'
import ContactMe from '../components/ContactMe'
import Link from 'next/link'


const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-thumb-[#F7AB0A] '>
      <Head>
        <title>Anurags Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      
        
      </Head>

      <Header/>
      {/*Hero */}
      <section id='hero' className='snap-start'>
      <Hero/>
      </section>
      {/*About*/}
      <section id='about' className='snap-center'>
        <About/>
      </section>

      <section id='experience' className='snap-center'>
        <Experience/>
      </section>
      {/*Skills*/}
      <section id='section' className='snap-start'>
        <Skilss/>
      </section>
      {/*Projects*/}
      <section id='project' className='snap-start '>
        <Projects/>
      </section>
      {/*Contact Me*/}
      <section id='contact' className='snap-start'>
        <ContactMe/>
      </section>
      
    </div>
  )
}

export default Home
